insert into estado(sigla, descricao) values ('TO', 'Tocantins');
insert into estado(sigla, descricao) values ('GO', 'Goiás');

insert into municipio(descricao, id_estado) values ('Goiania', 2);
insert into municipio(descricao, id_estado) values ('Anápolis', 2);

INSERT INTO municipio (descricao, id_estado) VALUES ('Abreulândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aguiarnópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aliança do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Almas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Alvorada', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ananás', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Angico', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aparecida do Rio Negro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aragominas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguacema', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguaçu', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguaína', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguanã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Arapoema', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Arraias', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Augustinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aurora do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Axixá do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Babaçulândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bandeirantes do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Barra do Ouro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Barrolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bernardo Sayão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bom Jesus do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Brasilândia do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Brejinho de Nazaré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Buriti do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cachoeirinha', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Campos Lindos', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cariri do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Carmolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Carrasco Bonito', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Caseara', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Centenário', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Chapada da Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Chapada de Areia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Colinas do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Colméia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Combinado', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Conceição do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Couto de Magalhães', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cristalândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Crixás do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Darcinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dianópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Divinópolis do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dois Irmãos do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dueré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Esperantina', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Fátima', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Figueirópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Filadélfia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Formoso do Araguaia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Fortaleza do Tabocão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Goianorte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Goiatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Guaraí', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Gurupi', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ipueiras', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itacajá', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itaguatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itapiratins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itaporã do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Jaú do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Juarina', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lagoa da Confusão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lagoa do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lajeado', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lavandeira', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lizarda', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Luzinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Marianópolis do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Mateiros', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Maurilândia do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Miracema do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Miranorte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Monte do Carmo', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Monte Santo do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Muricilândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nazaré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nova Olinda', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nova Rosalândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Acordo', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Alegre', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Jardim', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Oliveira de Fátima', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeirante', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeiras do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeirópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Paraíso do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Paranã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pau dArco', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pedro Afonso', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Peixe', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pequizeiro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pindorama do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Piraquê', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pium', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ponte Alta do Bom Jesus', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ponte Alta do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Porto Alegre do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Porto Nacional', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Praia Norte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Presidente Kennedy', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pugmil', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Recursolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Riachinho', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio da Conceição', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio dos Bois', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio Sono', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sampaio', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sandolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Fé do Araguaia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Maria do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Rita do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Rosa do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Tereza do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Terezinha Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Bento do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Félix do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Miguel do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Salvador do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Sebastião do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Valério da Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Silvanópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sítio Novo do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sucupira', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Taguatinga', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Taipas do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Talismã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tocantínia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tocantinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tupirama', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tupiratins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Wanderlândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Xambioá', 1);

INSERT INTO municipio (descricao, id_estado) VALUES ('Abreulândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aguiarnópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aliança do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Almas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Alvorada', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ananás', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Angico', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aparecida do Rio Negro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aragominas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguacema', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguaçu', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguaína', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguanã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Araguatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Arapoema', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Arraias', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Augustinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Aurora do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Axixá do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Babaçulândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bandeirantes do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Barra do Ouro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Barrolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bernardo Sayão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Bom Jesus do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Brasilândia do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Brejinho de Nazaré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Buriti do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cachoeirinha', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Campos Lindos', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cariri do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Carmolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Carrasco Bonito', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Caseara', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Centenário', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Chapada da Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Chapada de Areia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Colinas do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Colméia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Combinado', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Conceição do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Couto de Magalhães', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Cristalândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Crixás do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Darcinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dianópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Divinópolis do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dois Irmãos do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Dueré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Esperantina', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Fátima', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Figueirópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Filadélfia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Formoso do Araguaia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Fortaleza do Tabocão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Goianorte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Goiatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Guaraí', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Gurupi', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ipueiras', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itacajá', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itaguatins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itapiratins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Itaporã do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Jaú do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Juarina', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lagoa da Confusão', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lagoa do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lajeado', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lavandeira', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Lizarda', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Luzinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Marianópolis do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Mateiros', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Maurilândia do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Miracema do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Miranorte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Monte do Carmo', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Monte Santo do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Muricilândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nazaré', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nova Olinda', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Nova Rosalândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Acordo', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Alegre', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Novo Jardim', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Oliveira de Fátima', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmas', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeirante', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeiras do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Palmeirópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Paraíso do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Paranã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pau dArco', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pedro Afonso', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Peixe', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pequizeiro', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pindorama do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Piraquê', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pium', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ponte Alta do Bom Jesus', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Ponte Alta do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Porto Alegre do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Porto Nacional', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Praia Norte', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Presidente Kennedy', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Pugmil', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Recursolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Riachinho', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio da Conceição', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio dos Bois', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Rio Sono', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sampaio', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sandolândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Fé do Araguaia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Maria do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Rita do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Rosa do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Tereza do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Santa Terezinha Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Bento do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Félix do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Miguel do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Salvador do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Sebastião do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('São Valério da Natividade', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Silvanópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sítio Novo do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Sucupira', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Taguatinga', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Taipas do Tocantins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Talismã', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tocantínia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tocantinópolis', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tupirama', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Tupiratins', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Wanderlândia', 1);
INSERT INTO municipio (descricao, id_estado) VALUES ('Xambioá', 1);

insert into orgao(nome, sigla, id_municipio, ativo) values ('Tribunal de Justiça', 'TJTO', 1, true);
insert into orgao(nome, sigla, id_municipio, ativo) values ('Turma Recursal', 'TR', 1, true);
insert into orgao(nome, sigla, id_municipio, ativo) values ('Juízo da 1ª Vara Cível de Palmas', 'JVCP', 1, true);
insert into orgao(nome, sigla, id_municipio, ativo) values ('uízo da 1ª Vara Cível de Araguaína', 'JVCA', 2, true);

INSERT INTO endereco (id_municipio, id_estado, bairro, logradouro, numero)
VALUES (1, 1, 'Plano Dir. Sul', '1003 Sul', '1');
INSERT INTO endereco (id_municipio, id_estado, bairro, logradouro, numero)
VALUES (1, 1, 'Centro', 'Rua Principal', '10');
INSERT INTO endereco (id_municipio, id_estado, bairro, logradouro, numero)
VALUES (2, 1, 'Bela Vista', 'Avenida Secundária', '25');
INSERT INTO endereco (id_municipio, id_estado, bairro, logradouro, numero)
VALUES (1, 1, 'Jardim das Flores', 'Rua das Flores', '7');

INSERT INTO beneficiario (nome, cpf, rg, cpfPai, nis, dataNascimento, id_endereco)
VALUES ('Esther', '11111111111', '1111111', '22222222222', '111111', '2004-08-23', 1);
INSERT INTO beneficiario (nome, cpf, rg, cpfPai, nis, dataNascimento, id_endereco)
VALUES ('Isac', '22222222222', '2222222', '33333333333', '222222', '1990-05-15', 2);
INSERT INTO beneficiario (nome, cpf, rg, cpfPai, nis, dataNascimento, id_endereco)
VALUES ('Iad', '33333333333', '3333333', '44444444444', '333333', '1985-12-10', 3);
INSERT INTO beneficiario (nome, cpf, rg, cpfPai, nis, dataNascimento, id_endereco)
VALUES ('Tayse', '44444444444', '4444444', '55555555555', '444444', '2000-02-28', 4);

INSERT INTO usuario (nome, cpf, login, senha, nivel_sigilo, ativo)
VALUES ('Unitins', '12345678791', 'unitins', 'TRwn0XU29Gwl2sagG00bvjrNJvLuYo+dbOBJ7R3xFpU4m/FAUc5q8OoGbVNwPF7F5713RaYkN4qyufNCDHm/mA==',
        4, true);

INSERT INTO orgao_perfil (perfil, id_orgao, id_usuario) VALUES (1, 1, 1);

INSERT INTO atendimento (id_orgao, id_beneficiario, data_cadastro, id_usuario_inclusao, descricao, tipo_beneficio, situacao_atendimento)
    VALUES (1, 1, '2023-12-01', 1, 'Durante o cadastro do auxílio moradia para a família Melo, constatou-se que residem em uma casa de três quartos na Rua das Flores, número 123, bairro Esperança, Cidade Feliz. Embora a propriedade esteja em bom estado, enfrentam inundações sazonais, preocupando a segurança da família. A Sra. Melo pediu melhorias estruturais urgentes para proteger seus três filhos pequenos. Este cadastro é fundamental para um plano de assistência que melhore as condições habitacionais e a segurança da família.', 'Auxílio Moradia', 1),
        (1, 1, '2023-10-01', 1, 'Durante o cadastro do auxílio moradia para a família Melo, constatou-se que residem em uma casa de três quartos na Rua das Flores, número 123, bairro Esperança, Cidade Feliz. Embora a propriedade esteja em bom estado, enfrentam inundações sazonais, preocupando a segurança da família. A Sra. Melo pediu melhorias estruturais urgentes para proteger seus três filhos pequenos. Este cadastro é fundamental para um plano de assistência que melhore as condições habitacionais e a segurança da família.', 'Auxílio Moradia', 2);